#ifndef COMMONQTGUI_H
#define COMMONQTGUI_H
#include <QtGui/QtGuiDepends>
#include <QAccessible>
#include <QAccessiblebridge>
#include <QAccessibleObject>
#include <QAccessiblePlugin>
#include <QBitmap>
#include <QIcon>
#include <QIconEngine>
#include <QIconEnginePlugin>
#include <QImage>
#include <QImageIOHandler>
#include <QImageReader>
#include <QImageWriter>
#include <QMovie>
#include <QPicture>
#include <QPictureFormatPlugin>
#include <QPixmap>
#include <QPixmapCache>
#include <QStandardItemModel>
#include <QClipboard>
#include <QCursor>
#include <QDrag>
#include <QEvent>
#include <QGenericPlugin>
#include <QGenericPluginFactory>
#include <QGuiApplication>
#include <QInputMethod>
#include <QKeySequence>
#include <QOffscreenSurface>
#include <QPalette>
#include <QScreen>
#include <QSessionManager>
#include <QStyleHints>
#include <QSurface>
#include <QSurfaceFormat>
#include <QTouchDevice>
#include <QWindow>
#include <QGenericMatrix>
#include <QMatrix4x4>
#include <QQuaternion>
#include <QVector2d>
#include <QVector3d>
#include <QVector4d>
#include <QBackingStore>
#include <QBrush>
#include <QColor>
#include <QMatrix>
#include <QPagedPaintDevice>
#include <QPaintDevice>
#include <QPaintEngine>
#include <QPainter>
#include <QPainterPath>
#include <QPdfWriter>
#include <QPen>
#include <QPolygon>
#include <QRegion>
#include <QRgb>
#include <QTransform>
#include <QAbstracttextDocumentLayout>
#include <QFont>
#include <QFontDatabase>
#include <QFontInfo>
#include <QFontMetrics>
#include <QGlyphRun>
#include <QRawFont>
#include <QStaticText>
#include <QSyntaxHighlighter>
#include <QTextCursor>
#include <QTextDocument>
#include <QTextDocumentFragment>
#include <QTextDocumentWriter>
#include <QTextFormat>
#include <QTextLayout>
#include <QTextList>
#include <QTextObject>
#include <QTextOption>
#include <QTextTable>
#include <QDesktopServices>
#include <QValidator>
#include <QtGuiVersion>
#endif
